# Use Nginx base image
FROM nginx:latest

# Install openssl and apache2-utils for password file creation
RUN apt-get update && \
    apt-get install -y openssl apache2-utils && \
    rm -rf /var/lib/apt/lists/*

# Remove default Nginx configuration and add our custom configuration
RUN rm /etc/nginx/conf.d/default.conf
COPY docker/nginx.conf /etc/nginx/conf.d/
COPY docker/nginx_entrypoint.sh ./bin/
RUN chmod 0755 ./bin/nginx_entrypoint.sh
EXPOSE 8081

ENTRYPOINT ["./bin/nginx_entrypoint.sh"]
